exclude = [
  ".venv",
  "_build",
  "build",
  "dist",
  "__pypackages__",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  ".eggs",
  "*.egg-info",
  ".vscode",
  ".ipynb_checkpoints",
  "site-packages",
]

line-length = 88
indent-width = 4
target-version = "py313"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = [
  "F403" # F403: 'from module import *' used; unable to detect undefined names
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
quote-style = "double"
indent-style = "tab"
line-ending = "auto"
skip-magic-trailing-comma = false
